### ISSUE TITLE
Cannot seem to be able to get this to run corrrectly

### ISSUE THREAD

**Issue by Gotthorm** [managedcode/MAUIAppVersion#1]
When I run this, it always prints out the entire csproj file (with the expected changes) even if I do not set "print" to true, and yet it never actually modifies the original file.  
So it seems to just be failing gracefully?  Or I am missing a step?  I even looked at your test cases and didnt notice anything weird that I had not accounted for.

```  integrate-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update project file version
        uses: managedcode/MAUIAppVersion@v1
        with:
          csproj: ./Fe.csproj
          version: ${{ github.run_number }} # to keep value unique
          displayVersion: '1.2.3'
  
      - run: git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags

**Comment by KSemenenko** [comment]
Hello, let me check

**Comment by churchs19** [comment]
@Gotthorm - Looking at your workflow, it looks like you're never actually committing the changed file before trying to git push it back into the repo.

**Comment by Gotthorm** [comment]
> @Gotthorm - Looking at your workflow, it looks like you're never actually committing the changed file before trying to git push it back into the repo.

You were correct, thanks for pointing that out.  This was my first foray into GitHub actions and I seemed to have overlooked that part of it.
